### ISSUE TITLE
Ability to override parser errors to make them more meaningful?

### ISSUE THREAD

**Issue by trusktr** [eclipse-langium/langium#1086]
In this conversation, https://github.com/langium/langium/discussions/1045, I asked

> There's currently no way to hook in and provide better messages for certain parser errors? Would it even be feasible for that to be a feature?

@msujew replied

> Yeah, that should be feasible, but as of now the parser error message generator is hardcoded into Langium. It might make sense to extract it to a service though.

and @spoenemann asked to open an issue to track this idea, so here it is. :)

**Comment by spoenemann** [comment]
Thanks! Question: would it work to define a different `errorMessageProvider` in the parser config?

https://github.com/langium/langium/blob/0cd59e78a0b8e1dd681a379df2f1c06debee514a/packages/langium/src/parser/langium-parser.ts#L515

You should be able to override the default in your DI module:
```typescript
export const MyLanguageModule: Module<...> = {
    parser: {
        ParserConfig: {
            ...
        }
    }
};
```

**Comment by msujew** [comment]
Resolved by https://github.com/eclipse-langium/langium/pull/1108.
