### ISSUE TITLE
Export LSP services via dedicated ESM export

### ISSUE THREAD

**Issue by msujew** [eclipse-langium/langium#1166]
Currently, our LSP services (which rely heavily on the `vscode-languageserver` package) are exported through the main `langium` export. While this makes creating language servers very easy, it leads to a lot of unnecessary imports for adopters that don't want to build a language server, thereby increasing bundle size.

The long term plan (likely version 3.0, as it's a major breaking change) would be to export the LSP related services through a `langium/lsp` export. That way, adopters can choose to not to include those services.

**Comment by msujew** [comment]
@cdietrich Yes, I'll probably release a next version today/tomorrow.

**Comment by msujew** [comment]
@cdietrich New `next` release is available on npm :)

**Comment by cdietrich** [comment]
@msujew what is the replacement for
ServiceRegistry.getServices(uri) to obtain Services with lsp?

**Comment by sailingKieler** [comment]
> @msujew what is the replacement for ServiceRegistry.getServices(uri) to obtain Services with lsp?

@cdietrich for now you could do it the following way:
```
    const service: LangiumCoreAndPartialLSPServices = services.ServiceRegistry.getServices(uri);
    service.lsp?...
```
The `LangiumCoreAndPartialLSPServices` is available via `langium/lsp`.
Feel free to propose an alternative pattern. 😉

**Comment by cdietrich** [comment]
ok so i need to downcast ;)

**Comment by sailingKieler** [comment]
> ok so i need to downcast ;)

Yes. In case the LSP-related parts are available - which is the typical case - you get them via the `ServiceRegistry`.
It's just that we can't (don't want to) reference the LSP-related Symbol from the `ServiceRegistry` being part of the core components.

**Comment by spoenemann** [comment]
In a context where you know that LSP services are loaded, you can simply cast to LangiumServices.
