### ISSUE TITLE
include imported used rules in `railroad` result

### ISSUE THREAD

**Issue by Yokozuna59** [eclipse-langium/langium#1174]
Hi there, the current railroad result don't include rules are imported from another `.langium` file. I would like them to be included in the result.

![image](https://github.com/eclipse-langium/langium/assets/87622592/4b5edb99-a130-41fe-9b07-21f86c33c49d)

![image](https://github.com/eclipse-langium/langium/assets/87622592/d467b686-6f30-4d3d-bdcb-0e0ce86743c2)

**Comment by weedySeaDragon** [comment]
@Yokozuna59 - It is pulling in the imported 'common/common.langium' file.

The diagram does not include terminals (including hidden ones); terminals are filtered out before the diagram is created.

Do you want terminals to be shown?  Perhaps that could be an option.

**Comment by msujew** [comment]
@weedySeaDragon The issue is that the fragment parser rule `TitleAndAccessibilities` from common.langium is missing. Given that the generated syntax diagram includes imported rules, it only makes sense that the vscode extension should show those as well.

**Comment by weedySeaDragon** [comment]
Ah - now I see. I was totally overlooking that`TitleAndAccessibilities` was missing from the Info grammar diagram. 

I don't use VS code.  I have tweaked the code (langium-railroad) to make it easier for me create .html files and the results I have _do_ include the imported files.  
I haven't compared my code to the original yet to see why. When I do, I'll post info about the differences here, FWIW.
