### ISSUE TITLE
Completion provider ignores NodeDescriptions with the same name

### ISSUE THREAD

**Issue by dhuebner** [eclipse-langium/langium#1176]
Often a language accept different linking targets with the same name. A good example is method overloading.
Right now there is a `duplicateStore` in [complition-provider](https://github.com/eclipse-langium/langium/blob/7259652a1669e236688b6f1f062f92430dcfbfb6/packages/langium/src/lsp/completion/completion-provider.ts#L403) that prevents suggesting completions for same named NodeDescriptions. 
As we already provide a way to filter out NodeDescriptions from scope using `filterCrossReference(_nodeDescription)` I would like to suggest to remove the `duplicateStore`. In addition we can pass a `Set` to the `filterCrossReference` so the overwrites can use it as state, but I don't think it is required.

**Comment by dhuebner** [comment]
An other idea is to use `documentUri + path` as a set entry. This will filter out duplicate NodeDescriptions but accept descriptions with the same name.

**Comment by msujew** [comment]
Closed in https://github.com/eclipse-langium/langium/pull/1178
