### ISSUE TITLE
Slack GitHub integration

### ISSUE THREAD

**Issue by danieldietrich** [eclipse-langium/langium#1177]
Hi!
Our Slack integration broke after transferring the project from langium/langium to eclipse-langium/langium. Installing the Slack App  is common, other EclipseFdn projects also did install it.

I already [requested](https://github.com/apps/slack/installations/select_target) the Slack App installation. Could someone of the Owners @eclipsewebmaster please approve the request?

Thanks 🙏

**Comment by cdietrich** [comment]
@danieldietrich at Xtext / MWE we switched from slack to chat.eclipse.org. maybe this would be an option for langium too

**Comment by danieldietrich** [comment]
Thanks for the suggestion @cdietrich!
It should be no problem, though - other EclipseFdn projects use the Slack App, too...

<img width="573" alt="Screenshot 2023-09-01 at 13 56 22" src="https://github.com/eclipse-langium/langium/assets/743833/ad67596c-e4ae-4d05-abc7-42d9bdccc52e">

**Comment by spoenemann** [comment]
Requests to Eclipse admins generally go here: https://gitlab.eclipse.org/eclipsefdn/helpdesk
