### ISSUE TITLE
Wrong AST hierarchy on completion

### ISSUE THREAD

**Issue by cdietrich** [eclipse-langium/langium#1216]
given the grammar

```
grammar HelloWorld

entry Model:
    (myEnums+=MyEnum | ("call" expressions+=DotExpression))*
;
MyEnum:
    'enum' name=ID '{'
        literals+=MyEnumLiteral*
    '}'
;
MyEnumLiteral:
    name=ID
;

DotExpression infers Expression:
    Primary ({infer DotExpression.base = current} '.' target=DotTarget)*;

Expression:
    DotExpression;

Primary infers Expression:
    {infer Parenthesis} '(' expr=Expression ')' |
    RefExpression |
    NumberLiteral;

RefExpression:
    target=[MyEnum:ID];

NumberLiteral:
    value=INT
;

DotTarget:
   {infer DotTargetRef} ref=[MyEnumLiteral:ID] | {infer MyX} 'x' | {infer MyY} 'y';

hidden terminal WS: /\s+/;
ID returns string: ID1 | ID2;
terminal ID1: /[_a-zA-Z][\w_-]*/;
terminal ID2: /`[^`]*`/;
terminal INT returns number: /[0-9]+/;
terminal STRING: /"(\\.|[^"\\])*"|'(\\.|[^'\\])*'/;

hidden terminal ML_COMMENT: /\/\*[\s\S]*?\*\//;
hidden terminal SL_COMMENT: /\/\/[^\n\r]*/;

```

and this scope provider

```
import { EMPTY_SCOPE, DefaultScopeProvider, ReferenceInfo, Scope } from "langium";
import { isDotExpression, isDotTargetRef, isRefExpression } from "./generated/ast.js";

export class HelloWorldScopeProvider extends DefaultScopeProvider {

    override getScope(context: ReferenceInfo): Scope {
        if (context.property === 'ref' && isDotExpression(context.container)) {
            const memberCall = context.container;
            const previous = memberCall.base;
            if (!previous) {
                return super.getScope(context);
            }
            if (isRefExpression(previous)) {
                const t = previous.target.ref!
                return this.createScopeForNodes(t.literals)
            }
            return EMPTY_SCOPE;
        } else if (context.property === 'ref' && isDotTargetRef(context.container)) {
            const memberCall = context.container.$container;
            const previous = memberCall.base;
            if (!previous) {
                return super.getScope(context);
            }
            if (isRefExpression(previous)) {
                const t = previous.target.ref!
                return this.createScopeForNodes(t.literals)
            }
            return EMPTY_SCOPE;
        }
        return super.getScope(context);
    }

}
```

bound

```
    references: {
        ScopeProvider: services => new HelloWorldScopeProvider(services),
    }
```

when i do code completion on

```
enum MyEnum {
    Literal1 
    Literal2
}
call (MyEnum.|)
```

this seems to be caused by the AST hierarchy for the scope computation is off

```
- Model
  - Parenthesis 
     - // DotExpression missing here
     - DotTargetRef 

```

![Bildschirmfoto 2023-10-04 um 15 06 07](https://github.com/eclipse-langium/langium/assets/238736/62e009b5-0500-442c-b27d-2672747153ee)

is this intentional? how can i access the DotExpression in scoing in order to get access to the enum reference so that i can ask it for its literals?

side question:
is it intentional completion stops on the first context that has results (see `continueCompletion`)

**Comment by cdietrich** [comment]
am not sure if the synthetic node is the problem here.
or the context.

the the previousTokenFeatures the node is of type DotExpression, in the nextTokenFeatures it is Parenthesis

**Comment by msujew** [comment]
Ah, yes, the completion provider will create two contexts: One where we assume the user wants to finish completing what's before the cursor position (the DotExpression) or what's right at the cursor position (Parenthesis). In that sense, it's working as expected. That's exactly what the multiple contexts are for, and why the first context (what's before the cursor position) has priority (and will usually stop the completion process).

**Comment by cdietrich** [comment]
the question is what does "finish completing" completing mean.
does the right side of the `.` belong to the dotexpression?
i would assume yes.
so the rule `DotTarget` should be in the follow element list

**Comment by cdietrich** [comment]
i did some backtracking and back in Langium 1.2 this was working

**Comment by msujew** [comment]
Ok, so we were both right:
1. The synthetic element computation is doing something wrong, because `DotTargetRef` shouldn't appear as a direct child of `Parenthesis`.
2. We're missing a context that returns the end of the previous token. Thanks for the hint.

I've fixed point 2 in https://github.com/eclipse-langium/langium/pull/1239. Fixing point 1 isn't really useful, as we don't actually want a context with `Parenthesis` as its node there anyway.
