### ISSUE TITLE
Range of CST nodes after repeated tree rewriting

### ISSUE THREAD

**Issue by lars-reimann** [eclipse-langium/langium#1218]
Langium version: 2.0.2
Package name: langium

## Steps To Reproduce

1. Clone the repo linked below. It contains a slightly altered hello-world project that allows writing chained member accesses like `A.B` or `A.B.C`. For the member access directly below the root, a warning is issued.
2. Generate, build, and run the extension.
3. Create a new file with the `.hello` extension.
4. Type `A.B` into the file.
5. Type `A.B.C` into the file.

Link to code example: https://github.com/lars-reimann/langium-cst-range

## The current behavior

In step 4, the entire expression gets highlighted correctly:

![image](https://github.com/eclipse-langium/langium/assets/2501322/b7f4b621-8a91-4e44-9122-1863757cd663)

In step 5, however, only the part starting at the dot gets highlighted. The computed range of the CST node is also too short:

![image](https://github.com/eclipse-langium/langium/assets/2501322/1ee2b666-32cc-4a47-8803-82752174b3a1)

The [playground](https://langium.org/playground?grammar=OYJwhgthYgBAEgUwDbIPYHU0mQEwFD4CWAdgC6IgBmYAxorALJq4CuyDA3vrL7IgA8ADiEQBnMUTQkAXLACiw0RKkl8AX0KJyIAJ5MW7BqLKsQJMQbYcZPPoJHjJ0gLyNEEAEaUAgrXoS%2BADchKQU1HQMio4q0rCcmsTklDT0TB7eIH4BloIUJLiW0crOJPF2vKL0RABulHLFTqoVsBAZ9bAASohUlNr0GoTuXr7%2BTrAmZhYKSk3StnxdPX0kA4sAFC2LnMOZ2U4AdFWItZQutGai5JqLiwDkB3dbfG0jIC7dvVdrfACUAFTBULJCJpT4rNJ5bSFGYxUrlRYkSCIORiMggUjAQb4cHfYyIUzmSy4-oolqcEmrRDqWBItouACSABEgfgABZEXC4bSwcIQUhgZCwDAAZTkAHoADpiADU4pCfIFQuZEoA2gB9MAAWgAXj4tQAtAC6qslAHd1Ub-vL8EA&content=IIOgQiDCQ) (or a debugging session) shows that the AST is built properly:

```json5
{
  $type: "Module", 
  expression: 
  {
    $type: "MemberAccess", 
    receiver: 
    {
      $type: "MemberAccess", 
      receiver: 
      {
        $type: "Reference", 
        name: "A"
      }, 
      member: 
      {
        $type: "Reference", 
        name: "B"
      }
    }, 
    member: 
    {
      $type: "Reference", 
      name: "C"
    }
  }
}
```

## The expected behavior

The warning should be shown for the entire expression `A.B.C` in step 5. Likewise, the range of the CST node should be 0:0--0:5.

**Comment by msujew** [comment]
Might be related to the issue that https://github.com/eclipse-langium/langium/pull/932 attempts to fix. I'll probably take a look at that soon.
