### ISSUE TITLE
Custom rendering of tags in JSDoc comments

### ISSUE THREAD

**Issue by lars-reimann** [eclipse-langium/langium#1242]
The `JSDocDocumentationProvider` is a great default documentation provider. I'd like an easier means to customize the rendering of tags, however. For example, the first word after a `@param` tag might indicate the name of the parameter, which could be rendered as an inline code block.

A possible API would be to add a function

```ts
interface JSDocRenderOptions {
    renderTag?(tag: JSDocTag): string | undefined
}
```

This would also provide nice symmetry with the other properties of this interface (`tag`, `link`, `renderLink`).

Additionally, a method

```ts
protected documentationTagRenderer(node: AstNode, tag: JSDocTag): string | undefined
```

could be added to `JSDocDocumentationProvider`. By default, it could provide the prior behavior.

-----

If you are interested in this feature, I'd be willing to work on it.

**Comment by msujew** [comment]
@lars-reimann Sure, sounds like a reasonable thing to have included there as well 👍
