### ISSUE TITLE
cli command shown in "langium-quickstart.md" is not correct

### ISSUE THREAD

**Issue by tomsontom** [eclipse-langium/langium#1251]
Langium version: 2.0.0
Package name: langium-generator

## Steps To Reproduce

1. generate hello-world sample
2. try running the advertised `./bin/cli` which leads to the following error (on OS-X)
```
./bin/cli
zsh: no such file or directory: ./bin/cli
```

## The current behavior

Command shown langium-quickstart.md does not work.

## The expected behavior

Command shown in langium-quickstart.md should work unversially

## Possible ways to solve

- chmod `cli.js` to be executable and change command to `./bin/cli.js`
- change command to `node ./bin/cli.js`

If not mistaken although I think shebang-lines don't work on Windows so I think the proper way is to change the readme to use the 2nd option

**Comment by msujew** [comment]
@sailingKieler You fail to see it, because you have a Mac :)

I didn't work on Windows (as mentioned in the initial issue comment). Windows is fairly strict about what it accepts as an executable via the command line - which is why calling `node` first is necessary on Windows. Closing the issue.

**Comment by sailingKieler** [comment]
Indeed, I thought in that direction but the description says:
<img width="612" alt="image" src="https://github.com/eclipse-langium/langium/assets/8513883/6c14d9b5-e5a8-443a-899b-cc38ff8aa891">

**Comment by msujew** [comment]
Hm, I see. No idea, though using `node` should work anyway as expected ¯\\\_(ツ)\_/¯

**Comment by tomsontom** [comment]
@sailingKieler - correct the error from above is produced on my OS-X
- I use `yo langium` to bootstrap
- In the bin-directory there's no file named `cli` hence the file not found error is at least to me expected
- And as the file has not set the executable bit I don't understand why you can execute it

@msujew - on windows (unless you run in WSL) I don't think windows can do anything with `#!/usr/bin/env node` - at least I would be very suprised and according to https://stackoverflow.com/questions/10396305/npm-package-bin-script-for-windows it is simply ignored but I confess I have not tried but as you wrote using "node" is the safeway and works just anywhere.

**Comment by sailingKieler** [comment]
@tomsontom you're right, since v2.0 `./bin/cli` will be generated as `./bin/cli.js`. (I had v1.0.0 in my global installation.)

@msujew what the rational for this renaming? See https://github.com/eclipse-langium/langium/commit/eea5bc2b5621cc8a321c4b95d4ca63f0aa5324fe#diff-b4755ad3e38404bce97bf673a7adacacdac1a1def6788be6ad931a06728ad8ff

**Comment by tomsontom** [comment]
Well I think this how it is supposed to be in node/npm - if you package this up then npm automatically creates the wrapper so that the end user can really run "./bin/cli" - It is also mentionned in the stackoverflow link from above
