### ISSUE TITLE
Enforce isolation of package exports

### ISSUE THREAD

**Issue by spoenemann** [eclipse-langium/langium#1261]
It would be great to enforce that the main export of the `langium` package doesn't have any transitive dependencies to code from `test`, `grammar` (#1171) and `lsp` (#1258).

Can we write a test to detect such unwanted dependencies?

**Comment by kaisalmen** [comment]
Idea: Bundlers (e.g.) do module graph analysis. We could use a plugin to access that graph and perform analysis / search / identification.

**Comment by spoenemann** [comment]
I found a simple solution in #1269.
