### ISSUE TITLE
Type hierarchy provider

### ISSUE THREAD

**Issue by lars-reimann** [eclipse-langium/langium#1275]
LSP 3.17 added a way to get the subtypes/supertypes of an entity, based on three requests:
* [textDocument/prepareTypeHierarchy](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_prepareTypeHierarchy)
* [typeHierarchy/supertypes](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#typeHierarchy_supertypes)
* [typeHierarchy/subtypes](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#typeHierarchy_subtypes)

It would be nice to be able to easily hook into this, similar to the `CallHierarchyProvider`.

I'm currently working on this for a Langium-based DSL:
* [TypeHierarchyProvider](https://github.com/Safe-DS/DSL/blob/bdd3116c7e4d3a4da15006b7ed2822826b39a621/packages/safe-ds-lang/src/language/lsp/safe-ds-type-hierarchy-provider.ts#L27C21-L27C21)
* [AbstractTypeHierarchyProvider](https://github.com/Safe-DS/DSL/blob/bdd3116c7e4d3a4da15006b7ed2822826b39a621/packages/safe-ds-lang/src/language/lsp/safe-ds-type-hierarchy-provider.ts#L39C23-L39C52)
* [request handler](https://github.com/Safe-DS/DSL/blob/bdd3116c7e4d3a4da15006b7ed2822826b39a621/packages/safe-ds-lang/src/language/lsp/safe-ds-language-server.ts#L123)

The interface is basically a copy of the `CallHierarchyProvider`. If you'd accept such a PR, I'd like to move the interface, the no-op implementation, and the request handler up into Langium.

**Comment by msujew** [comment]
Sure, that sounds pretty good. We'd love a contribution in that direction 👍
