### ISSUE TITLE
Testing facilities generated out of the box 

### ISSUE THREAD

**Issue by acherm** [eclipse-langium/langium#1282]
Hi, 

I hope new versions of Langium generator will offer the ability to generate testing facilities out of the box, as part of the DSL project. 
It was a bit the case with Xtext, with an `***/test` package and a `parseHelper` ready to use https://eclipse.dev/Xtext/documentation/103_domainmodelnextsteps.html#tutorial-unit-tests 

As part of my experience with setting such testing facilities (see https://dev.to/diverse_research/testing-your-dsls-in-langium-gp9), I encountered two issues: 
 * lack of understanding of the testing API... there will be a tutorial: https://github.com/eclipse-langium/langium-website/issues/203 and it's super nice!
 * an integrated and ready-to-use solution with `package.json` containing a `test` command, a configuration file of `vite`, and the boilerplate almost described here https://dev.to/lotes/comment/2aiog or in the post
 
Not only DSL developers will enjoy a testing facility out of the box and ready-to-use, but it will enforce best practices, and not forcing developers to dig into the API/documentation. 

I am seeing it as a "feature" of the langium generator, and perhaps a flag or a configuration option somewhere should be introduced to generate or not testing facilities. 

Kudos for the great work! 

Mathieu

**Comment by sailingKieler** [comment]
Contributed with #1298.
