### ISSUE TITLE
Parse error, but still yields a correct AST

### ISSUE THREAD

**Issue by rolandzwaga** [eclipse-langium/langium#1297]
Langium version: 2.1.2
Package name: langium

## Steps To Reproduce

1. Check this [playground url](https://langium.org/playground?grammar=OYJwhgthYgBAogGwJbGQVwM4ChsFMA7AFxAE9YB5ABz3COQHsCAubWd2TUzIvCAOUh4AvPwCCAWXiwA5AAoZsOTGDoIhIpgDUooQBMxIVeuJKZAGkUq1G7bvUGjN4gEoAVO9kuZAblyCHQ2MNVg5YAiFRSWl4AEUAVTEAGQBlWAA3MER0ETkUgBUAJQBJfgBxAB9%2BeIkAIXhCquiKlPgk%2BABhfIpG2ooKJIB9Ivj4Cr6BwYAxZNaXP2wAC2Q9PUJYXhAIZAjEWAB1FOZYAHoAHW0Tv03t3dhW9q6e4-OAOgqzgGIAbTOAWjAfwAXmI-gAtAAMfwAnABdLRXbA3HZZBAJWYvM7COQAfmEZwARi5Eci7hMhiNpCA8ER0CACJhYASGAxEHgwCxTiQcrj8USSbRbqjydNZlSaXSGUyWWyOS8AGZZTB4XmE4nXQUovYFErlTEAIm%2BAD0zvr4aaBVstbBxFIXt9ASDwVDof9BvDLUK9tU6g1YNTafTGQQ1ATaPaXR6FstVutSaiJEMOhQJFJ%2BPlMec3L9MGcUrC3Dizm4zidETG1gQNpq7ikkym0xnTqXS8azgQziAC4igA&content=M4UwNiDGAuCiEFsQDtoApQRgewE4F4BiBAQwEtkBaaM6CASgCgg)

Link to code example:

 [playground url](https://langium.org/playground?grammar=OYJwhgthYgBAogGwJbGQVwM4ChsFMA7AFxAE9YB5ABz3COQHsCAubWd2TUzIvCAOUh4AvPwCCAWXiwA5AAoZsOTGDoIhIpgDUooQBMxIVeuJKZAGkUq1G7bvUGjN4gEoAVO9kuZAblyCHQ2MNVg5YAiFRSWl4AEUAVTEAGQBlWAA3MER0ETkUgBUAJQBJfgBxAB9%2BeIkAIXhCquiKlPgk%2BABhfIpG2ooKJIB9Ivj4Cr6BwYAxZNaXP2wAC2Q9PUJYXhAIZAjEWAB1FOZYAHoAHW0Tv03t3dhW9q6e4-OAOgqzgGIAbTOAWjAfwAXmI-gAtAAMfwAnABdLRXbA3HZZBAJWYvM7COQAfmEZwARi5Eci7hMhiNpCA8ER0CACJhYASGAxEHgwCxTiQcrj8USSbRbqjydNZlSaXSGUyWWyOS8AGZZTB4XmE4nXQUovYFErlTEAIm%2BAD0zvr4aaBVstbBxFIXt9ASDwVDof9BvDLUK9tU6g1YNTafTGQQ1ATaPaXR6FstVutSaiJEMOhQJFJ%2BPlMec3L9MGcUrC3Dizm4zidETG1gQNpq7ikkym0xnTqXS8azgQziAC4igA&content=M4UwNiDGAuCiEFsQDtoApQRgewE4F4BiBAQwEtkBaaM6CASgCgg)

## The current behavior
Check the red squiglies underneath '=#main-title', when mouse-overing it reports the error 'expecting the token EQUALS but found #main-title'.
Then check the AST column, the NamedArgument instance has a value of '#main-title'

## The expected behavior

I would expect no parsing error to occur, because the AST is exactly what I expect.
Of course, I might do something very, very wrong in my grammar, in which case I would really appreciate some guidance.

Thank you in advance!

**Comment by spoenemann** [comment]
The error is likely due to the way how you defined EQUALS (with positive lookahead). Changing to a simple `'='` keyword fixes it:

```
NamedArgument:
    name=NAME '=' value=Value;

Value returns string:
    STRING | NUMBER | NAME | SELECTOR | BOOL_TRUE | BOOL_FALSE;
```

Here I also extracted the value to a `string` typed rule.

**Comment by msujew** [comment]
Note that there are actually two red squiggles (right after another):

![image](https://github.com/eclipse-langium/langium/assets/4377073/acd06314-0545-408d-a434-b0dbc0e5e653)

The first one indicates that the `=` sign couldn't be lexed (due to the issue outlined above by @spoenemann), while the other indicates that `EQUALS` had to be skipped in order to parse the input.

**Comment by rolandzwaga** [comment]
Argh, thank you gentleman, the problem was indeed the defintion of my terminal. The grammar I posted was a simplified version of my real grammar. I now see that I ordered some terminals wrong there. In an effort to try and fix the problem I was trying out all sorts of things and had added the look-aheads.
Not realising this actually just made matters worse...

Thank you for your time!
