### ISSUE TITLE
Completion Problem due to Parser Error

### ISSUE THREAD

**Issue by csalve** [eclipse-langium/langium#1302]
Hi,

I have a problem with the auto completion for my DSL.
I have following grammar:

```
entry Model:
    (structs+=Struct | attributes+=Attribute)*;

Attribute:
    '@' id=INT 'attribute' name=ID;

Struct:
    'struct' name=ID '{'
        (members+=Member)*
    '}';

Member:
    StringMember | IntegerMember;
fragment MemberDetails:
    '@' id=INT
    name=ID ':';

IntegerMember:
    MemberDetails
    (type='uint' | type='int');

StringMember:
    MemberDetails
    (type='string' | type='nanoid');
```

When I define a _member_ inside a _struct_ in this language, I expect to get a proposal of one of the specific types (_int_, _uint_, _string_, _nanoid_) but this is not working:

![image](https://github.com/eclipse-langium/langium/assets/77828558/3bfddde8-9063-4e73-a2a9-2b1b2aa06215)

Instead, I get a proposal for the attribute where it is not expected, see here:
![image](https://github.com/eclipse-langium/langium/assets/77828558/8ec21272-4eb1-4254-a3cf-61ff2f96d582)

The struct member is parsed correcly only if its definition is complete. Obviously, then it is to late for auto completion.

I had a look if it is maybe a problem of the completion provider, but it seems that already the parser is causing the problem. The parser somehow parses the member as attribute.

I tested with langium version: 2.1.0

**Comment by msujew** [comment]
Hey @csalve,

yeah, looking at the CST that is being produced by the given input, I can definitely see that it tries to generate a `Attribute` node instead of continuing with the `Struct` rule.

Given that we have limited influence on the error recovery in Langium, I would instead recommend to restructure your grammar a bit. The main issue here is that you have an alternative with a fairly large prefix:

![image](https://github.com/eclipse-langium/langium/assets/4377073/08c1cb09-69be-4877-b2f7-7a66b4e0ad94)

By removing this prefix, we can get a way better completion result:

![image](https://github.com/eclipse-langium/langium/assets/4377073/2f4c8eb4-47d7-4669-975f-da0adaab6728)


See the improved grammar below:

<details>

```
entry Model:
    (structs+=Struct | attributes+=Attribute)*;

Attribute:
    '@' id=INT 'attribute' name=ID;

Struct:
    'struct' name=ID '{'
        (members+=Member)*
    '}';

Member:
    '@' id=INT
    name=ID ':' ({infer IntegerMember} (type='uint' | type='int') | 
                 {infer StringMember} (type='string' | type='nanoid'));
```

</details>

**Comment by csalve** [comment]
@msujew Thanks for your help.

The improved grammar solves the issue with the parser but opens two new problems.
I tried to implement your suggestion in two different ways and both of them lead to problems/errors with the ast.

# Using Interfaces
The documentation tells me, that it is good practice to define interface types.
So I did:
```
interface IntegerMember {
    type:string
}
interface StringMember {
    type:string
}
Member:
    '@' id=INT
    name=ID ':'
    (
        {IntegerMember} (type='uint' | type='int') |
        {StringMember} (type='string' | type='nanoid')
    );
```

But the generated AST does not give me the possibility to access the 'type' variable.
There is no relation between IntegerMember and Member:
```
export interface IntegerMember extends AstNode {
    readonly $type: 'IntegerMember';
    type: string
}

export interface Member extends AstNode {
    readonly $container: Struct;
    readonly $type: 'Member';
    id: number
    name: string
}
```

# Infer types without interfaces

Using the improved grammar as above creates a good AST:

```
export interface Member extends AstNode {
    readonly $type: 'IntegerMember' | 'Member' | 'StringMember';
    id: number
    name: string
}

export interface IntegerMember extends Member {
    readonly $type: 'IntegerMember';
    type: 'int' | 'uint'
}

export interface StringMember extends Member {
    readonly $type: 'StringMember';
    type: 'nanoid' | 'string'
}
```

Problem here: The 'name' and 'id' of the Member struct is never set:

![image](https://github.com/eclipse-langium/langium/assets/77828558/1c5027d8-5b2e-45fd-9b0f-22d5ebf08adc)

In both described cases, langium violates the type system.

**Comment by msujew** [comment]
@csalve Right, I forgot that using the actions syntax removes all previous properties. We kind of inherited that behavior from Xtext and never bothered to change it. You should be good without using it:

```
Member:
    '@' id=INT
    name=ID ':'
    (
        type='uint' | type='int' |
        type='string' | type='nanoid'
    );
```

You can write your own `isStringMember` function if you need to that checks the value of the `type` property on a `Member` type.

**Comment by msujew** [comment]
Since this is a known (but unfixable on our side) issue, and it can be worked around by improving the grammar design, I'll close this.
