### ISSUE TITLE
getTypeMetaData does not consider returned types

### ISSUE THREAD

**Issue by cdietrich** [eclipse-langium/langium#1371]
Given the grammar

```
interface IAmArray {
   elements: ArrayContent[];
}
interface DeclaredArray extends IAmArray{ }

DeclaredArray returns DeclaredArray:
     'declared' (elements+=ArrayContent)* ';';

ArrayContent:
    name=ID;
```

`AstReflection.getTypeMetaData` wont flag the elements of DeclaredArray as array and thus it wont have a default value

**Comment by cdietrich** [comment]
alternatively: `assignMandatoryAstProperties` should also check return types.

**Comment by msujew** [comment]
The issue is that the generated ast reflection currently only considers properties of the current interface, not of the whole interface chain:

https://github.com/eclipse-langium/langium/blob/1f5d1246692aafb70672fb6ce695fefc4e54767c/packages/langium-cli/src/generator/ast-generator.ts#L84

**Comment by cdietrich** [comment]
nice. thx for the fix. works now as expected
