### ISSUE TITLE
Nodes that consume no text are undefined

### ISSUE THREAD

**Issue by drhagen** [eclipse-langium/langium#1398]
Langium version: 3.0.0

When a node succeeds but consumes no input, it is `undefined` rather than a well-defined `AstNode` object.

Consider this grammar:

```langium
grammar HelloWorld

entry Model:
    'header' persons=Persons;

Persons:
    ((elements+=ID) (elements+=ID)*)?;

hidden terminal WS: /\s+/;
terminal ID: /[_a-zA-Z][\w_]*/;
```

when parsing this file:

```
header
```

When there are no persons listed, I would expect the resulting AST to be something like `{persons: {elements: []}}`. Instead, it is `{persons: undefined}`.

**Comment by msujew** [comment]
This is by design, the parser will never attempt to construct synthetic AST nodes (which `{elements: []}` would be) and doing so likely leads to very unexpected behavior, as there is no CST to associate to it.

**Comment by drhagen** [comment]
That makes sense. If it is not a node but merely an attribute, it is still expected that the result is undefined? For example, this grammar

```langium
grammar HelloWorld

entry Model:
    'header'
    (persons+=ID ('+' persons+=ID)*)?
;

hidden terminal WS: /\s+/;
terminal ID: /[_a-zA-Z][\w_]*/;
```

when parsing 

```
header
```

also generates the AST `{persons: undefined}`.

This is unexpected because the generated interface does not say this is an optional attribute:

```typescript
export interface Model extends AstNode {
    readonly $type: 'Model';
    persons: Array<string>;
}
```

**Comment by drhagen** [comment]
> On the other hand, the AST is guaranteed to align to the generated types in case the parser returns without any errors.

`header` is a valid document for the parser in my previous message. It parses without error, but `model.person` is still `undefined` during validation of `Model`. Does the validation code run before parsing is complete and the default values are assigned?

**Comment by msujew** [comment]
> It parses without error, but model.person is still undefined during validation of Model.

Yes, that's exactly why I said it's supposed to be a grammar error. It produces a nonsensical AST, even on correct input, because the grammar isn't written in a correct way. My thoughts are: correct grammar + correct input = correct AST.

> Does the validation code run before parsing is complete and the default values are assigned?

No, validation is the last phase of the document lifecycle, see [here](https://langium.org/docs/document-lifecycle/).
