### ISSUE TITLE
hello-world-generation-not-works-anymore

### ISSUE THREAD

**Issue by asatklichov** [eclipse-langium/langium#1519]
Hi there, 

One month ago, when I tried to create new project, it worked with hello-world example.
"person Martin;
Hello Martin!;
"

Today I tried it again, but lsp-server does not react, it does not show neither highlight, nor suggestions. 
Project generations steps are successful,  but not works as before. 

Thanks you in advance,
Azat

**Comment by msujew** [comment]
Hey @asatklichov,

the latest version of [generator-langium](https://www.npmjs.com/package/generator-langium/v/3.0.0) is 3 months old. We haven't published any update to Langium or the yeoman generator in the past few months.

I just tried out the yeoman generator for myself and can confirm that everything works as expected. The resulting project is functional and the language is highlighted/handled correctly in the editor. Can you provide a reproducible example repo?

**Comment by asatklichov** [comment]
Hi @msujew thank you for double checking, please try: https://github.com/asatklichov/pl1-with-langium/tree/main/bahbit-bola
which I generated yesterday for PL1 language (not yet changed the grammar - still hello world is there).
Last time it worked, it stopped lsp-support now, my guess was I installed IBM pl1 support extension in VSCode (may cause a clash), but later uninstalled it, still same above repo not works

**Comment by msujew** [comment]
@asatklichov I've just tried https://github.com/asatklichov/pl1-with-langium but everything works as expected for me:

![image](https://github.com/eclipse-langium/langium/assets/4377073/308fef9f-eef0-401d-8742-7ebdd1d30510)

Are you actually starting the second VSCode instance via the `Run Extension` debug launch configuration? Does VSCode register your `.pl1` files as belonging to the `bahbit-bola` language id (should be shown in the lower right corner)?
