### ISSUE TITLE
Default class implementations do not fully implement interfaces

### ISSUE THREAD

**Issue by snarkipus** [eclipse-langium/langium#1584]
Langium version: 3.1.x
Package name: Langium

## Steps To Reproduce

1. See issue #1579 

Link to code example:
```typescript
export interface DocumentSymbolProvider {
    ...
    getSymbols(document: LangiumDocument, params: DocumentSymbolParams, cancelToken?: CancellationToken): MaybePromise<DocumentSymbol[]>;
}


export class DefaultDocumentSymbolProvider implements DocumentSymbolProvider {
    ...
    getSymbols(document: LangiumDocument): MaybePromise<DocumentSymbol[]> {
        return this.getSymbol(document, document.parseResult.value);
    }
    ...
}
```

## The current behavior
Some `DefaultXYZProvider` classes do not fully implement their corresponding interface. Due to TypeScript's structural typing, this is allowable but may prevent proper subclassing and/or overriding of default methods.

## The expected behavior
Where appropriate, `DefaultXYZ` classes should fully implement their corresponding interfaces and/or provide documentation regarding the implementation.

## Notes
<img width="245" alt="image" src="https://github.com/user-attachments/assets/ef09dcdc-a7da-4f15-a2ed-dad836869a75">

**Comment by snarkipus** [comment]
@msujew I'm working through this cleanup and you had originally marked a lot of these interfaces with `@throw ...` which makes sense to me if the `CancellationToken` is handled.  Do these throw in a non-obvious way in the absence of the canceltoken (unused in most/all of these default class implementations)? If not, I'll just delete the comments during the clean-up.

**Comment by snarkipus** [comment]
@msujew This ended up being a larger endeavor than expected. I assume you guys might want to review the changes prior to me submitting a PR.

Here is the commit if you'd like to look it over before I submit: https://github.com/snarkipus/langium/commit/f492be907443d48ed11563732a65968360842db1

## Assumptions:
- Respect the interface definition (I didn't attempt to determine their correctness)
- All DefaultXYZ class implementations are intended to be extended by an end-user (probably a bit bold)
- Don't break anything (tests are handy - although cancellation testing might be something painful and interesting)
## Change Summary (inspired by Claude who can apparently read git diff redirects):
- Updated error handling for OperationCancelled events, consistently re-throwing them when detected.
- Updated cancellation token handling, using a default `CancellationToken.None` when not provided.
- Updated JSDoc comments with more detailed parameter and return value descriptions.
- Removed ResponseError throws from method signatures, as they're no longer explicitly thrown.
- Added default implementations for some interface methods
- Improved type safety and consistency in various method signatures.
- Refactored several methods to use optional parameters instead of default values.

These changes focus on updating error handling, cancellation support, and overall code consistency.

**Comment by spoenemann** [comment]
Thanks! Most of the changes look good, so I think a PR would be great to discuss the details.

Two questions beforehand:

> Updated error handling for OperationCancelled events, consistently re-throwing them when detected.
I don't understand the intent of wrapping calls to `interruptAndCheck` in try-catch blocks:
```
           try {
                await interruptAndCheck(token);
            } catch (error) {
                if (isOperationCancelled(error)) {
                    throw error; // re-throw OperationCancelled
                }
            }
```

> Removed ResponseError throws from method signatures, as they're no longer explicitly thrown.

It's true that the current code doesn't use that, but I would still leave it in the documentation because it can be useful in custom implementations of LSP services to throw a ResponseError so the client gets a more accurate description of the error state.

**Comment by snarkipus** [comment]
> I don't understand the intent of wrapping calls to `interruptAndCheck` in try-catch blocks:

Functionally, it doesn't do anything - the thought was simply to reflect the guidance provided in the `isOperationCancelled()` implementation as an example. Happy to remove/revert if you think a comment is sufficient.
```typescript
/**
 * Use this in a `catch` block to check whether the thrown object indicates that the operation
 * has been cancelled.
 */
export function isOperationCancelled(err: unknown): err is typeof OperationCancelled {
    return err === OperationCancelled;
}
 ```
 > It's true that the current code doesn't use that, but I would still leave it in the documentation because it can be useful in custom implementations of LSP services to throw a ResponseError so the client gets a more accurate description of the error state.
 
I can put them back in - no problem. Similar rationale as `OperationCancelled`, it just wasn't immediately obvious to me where or how to handle `ResponseError`.
 
 Once I hear back on this, I'll make the updates and submit a PR. :)

**Comment by spoenemann** [comment]
> > I don't understand the intent of wrapping calls to `interruptAndCheck` in try-catch blocks:

> Functionally, it doesn't do anything - the thought was simply to reflect the guidance provided in the `isOperationCancelled()` implementation as an example. Happy to remove/revert if you think a comment is sufficient.

Yes I'd rather revert that. The idea is that when you use `interruptAndCheck`, you don't need to check the result immediately. We rather catch a possible thrown `OperationCancelled` at a higher level in the call stack, where we create proper response messages.

>> It's true that the current code doesn't use that, but I would still leave it in the documentation because it can be useful in custom implementations of LSP services to throw a ResponseError so the client gets a more accurate description of the error state.

> I can put them back in - no problem. Similar rationale as `OperationCancelled`, it just wasn't immediately obvious to me where or how to handle `ResponseError`.

Yes let's keep those for now.
