### ISSUE TITLE
`langium` package cannot be tree-shaken well

### ISSUE THREAD

**Issue by jindong-zhannng** [eclipse-langium/langium#1642]
**Reproduction**: https://github.com/jindong-zhannng/langium-bundle-test
**Bundler**: vite

There is only one import in `main.ts` (to simulate the case of `generated/ast.ts`): 

```ts
import { AbstractAstReflection } from 'langium'
```

And class `AbstractAstReflection` also has **zero** dependency.

**Expect**: Bundle should only include `AbstractAstReflection` relevant code.
**Actual**:

![image](https://github.com/user-attachments/assets/4b6d66cf-641d-4f05-8ec1-29e80a36e7b3)

*(run `npx vite-bundle-visualizer --open -o ./stats.html` to generate report)*

Obviously it includes lots of dead code like parser, validator and their dependencies. It brings the bundle size up to 174.67 kB (minified).

**Idea**

I tried to add ` "sideEffects": false` to `package.json`. It significantly reduces the size to 1.27 kB and has a perfect report:

![image](https://github.com/user-attachments/assets/61a582c5-3df8-4e29-ad42-44801859450f)

I'm not sure if it's suitable for langium and I also don't have a very good understanding of this setting. Just put it here for your reference.

**Comment by msujew** [comment]
Hey @jindong-zhannng,

thanks for the investigation. Since we actually don't feature any side effects, I've filed https://github.com/eclipse-langium/langium/pull/1643. It will be released as part of 3.2 (hopefully next week).
