### ISSUE TITLE
Add an option to suppress Chevrotain warnings

### ISSUE THREAD

**Issue by aabounegm** [eclipse-langium/langium#1687]
Sometimes, when the grammar is too complicated, Chevrotain would print to the console warnings like this:
```
Ambiguous Alternatives Detected: <0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1> in <OPTION2> inside <Tag​> Rule
```
Which are not always very informative, but also mainly they flood the user's console. While they might signal real issues with the grammar, sometimes these ambiguities are unavoidable.
It would be great if there is an option to turn these warnings off, at least in production mode.

**Comment by aabounegm** [comment]
@dhuebner I remember you said you had a project in which you were able to suppress these warnings. Can you please share the workaround (temporarily, until it is implemented in Langium)?

**Comment by dhuebner** [comment]
@aabounegm
Sure. In the [BBj LS project](https://github.com/BBx-Kitchen/bbj-language-server/) we suppress all this ambiguity warnings and just report it once in debug log. The solution is a bit hacky, so I think we should have an easier nook to customize the behavior.

[Here is the parser adjustment.](https://github.com/BBx-Kitchen/bbj-language-server/blob/b7d1dd6f140dcd4428cdcbc73d248e9b7c8529a4/bbj-vscode/src/language/bbj-module.ts#L92)

**Comment by msujew** [comment]
See https://github.com/eclipse-langium/langium/pull/1688 for a fix for this.

**Comment by aabounegm** [comment]
@dhuebner Thanks a lot! That should help at least until the PR above is merged and released
