### ISSUE TITLE
Registered Document Paths on Windows

### ISSUE THREAD

**Issue by georg-schwarz** [eclipse-langium/langium#1725]
Langium version: `3.1.0`, but should also concern `3.2.0`
Package name: `langium/utils`

## Steps To Reproduce

1. Use a Windows machine
2. Create a new custom workspace manager, extending the `DefaultWorkspaceManager`, overwriting the 
```javascript
override async initializeWorkspace(
    folders: WorkspaceFolder[],
    cancelToken = CancellationToken.None,
  ): Promise<void> {
    const documents = await this.performStartup(folders);

    documents.forEach((document) => {
      console.log(`Loading document: ${document.uri.toString()}`);
    });
  // ...
```
4. Register the custom workspace manager in the langium module
5. Initialize the workspace manager with a directory
```javascript
await services.shared.workspace.WorkspaceManager.initializeWorkspace(
  workspaceFolders,
);
```

In our case, this caused problems when getting documents based on a user-defined file path:
```javascript
const document = services.shared.workspace.LangiumDocuments.getDocument( 
   URI.file(path.resolve(filePath)), 
 ); // resolved to undefined, even though file was in registered working directory
```

## The current behavior

Logs sth like the following (incorrect Windows path, see last `/` as separator):
```
Loading document: C:%5CUsers%5Cjohan%5Cworkspaces%5Cjayvee%5Cexample/state-codes.jv
```

## The expected behavior

Logs sth like the following (correct Windows path):
```
Loading document: C:%5CUsers%5Cjohan%5Cworkspaces%5Cjayvee%5Cexample%5Cstate-codes.jv
```

## Further Notes

I drilled down into the Langium codebase and traced the method calls:
- It uses the `readDirectory` method https://github.com/eclipse-langium/langium/blob/b52cb60f097fd6046f6265e3e72a9cee253df061/packages/langium/src/node/node-file-system-provider.ts#L22-L30
- Which uses the `UriUtils`.
https://github.com/eclipse-langium/langium/blob/b52cb60f097fd6046f6265e3e72a9cee253df061/packages/langium/src/utils/uri-utils.ts#L23-L38
The issue should be in line 35, where `/` is used as a hard-coded path separator.

**Comment by msujew** [comment]
@georg-schwarz I believe your URIs are double encoded - they are missing the URI scheme. Running `uri.toString()` should not escape the `/` characters. I just tried your reproduction steps on Windows (I'm on Windows myself) and failed to reproduce:

![grafik](https://github.com/user-attachments/assets/61d0a89f-e028-46c2-9a4c-ec54556a20b2)

**Comment by georg-schwarz** [comment]
How come you have forward slashes on Windows file paths?

**Comment by msujew** [comment]
@georg-schwarz Because URIs != file paths. We only process URIs in Langium. They are specced to use `/` as separators.

**Comment by msujew** [comment]
@georg-schwarz Looking at your implementation in your CLI (see [here](https://github.com/jvalue/jayvee/blob/e1ddf2264c78c4b8f4c94d5f11545282f144626b/libs/interpreter-lib/src/parsing-util.ts#L67), you're using `URI.parse` to parse a file path into a URI - however, you are only supposed to put valid URIs into that function. For transforming file paths into URIs, please use `URI.file` instead.

**Comment by georg-schwarz** [comment]
@msujew Thank you for your fast response and the support beyond! 
We definitely mixed sth up there (see your explanations on uris vs. file paths). 
I'm positive we can make it work from here.

**Comment by msujew** [comment]
@georg-schwarz You're welcome. I was curious how you created those double encoded URIs. I forgot that using `URI.parse` on Windows file paths yields "valid" URIs, since the `c:` gets interpreted as the scheme of the URI, while everything else just ends up as the path and gets encoded on `toString()`. However, that usually isn't the intentation :D

**Comment by georg-schwarz** [comment]
Our original implementation (before some weird work around) was something like this:

```javascript
const workingDir = process.cwd();
const workspaceFolders = [{
  name: 'projectRoot',
  uri: path.resolve(workDir)
}];
await services.shared.workspace.WorkspaceManager.initializeWorkspace(
    workspaceFolders,
);
```

I think we also tried some variations with `URI.file(workingDir)`, but I'll have to try it again to find out where the issue was with that approach :) I think we just need a proper way to turn the output of `process.cwd()` into a valid URI, and then we should be good to go :)
