### ISSUE TITLE
Langium Language Server Crashes with "TypeError: Cannot read properties of undefined (reading 'localeCompare')"

### ISSUE THREAD

**Issue by c-classen** [eclipse-langium/langium#1728]
When using the word `type` in a Rule following another Rule that is not terminated with a `;`, the Langium language server crashes.

Langium version: 3.2.0

## Steps To Reproduce

1. Create a new prject using the steps from the [Langium documentation](https://langium.org/docs/learn/workflow/scaffold/) and choose the defaults.
2. Open the project in Visual Studio Code
3. Paste the following code into the `hello-world.langium`:

```
grammar HelloWorld

entry Model:
    NonTerminatedRule

NonTerminatedRule:
    'hello' RuleWithType

RuleWithType:
    type='String'
```

I know the syntax is not valid, but I still expect the language server not to crash, because I have to restart Visual Studio Code each time that happens.

**Comment by msujew** [comment]
This has actually already been resolved, see https://github.com/eclipse-langium/langium/pull/1634. Our automated release job failed, because Microsoft decided to revoke our automation token (I don't know why).

I published the newest version of 3.2.0 manually. Closing.
