### ISSUE TITLE
Provide CLI utilities in Langium

### ISSUE THREAD

**Issue by msujew** [eclipse-langium/langium#239]
To improve development speed for CLIs build on Langium, we need to provide utilities for different CLI specific issues:

* Initializing workspaces based on file paths
* Interacting with the shell in different ways (colors, reading input, etc.)
* Watch ability which correctly updates documents based on file system events

**Comment by spoenemann** [comment]
Note: We should avoid adding dependencies to the base package for these utilities. Would it be an option to offer some utilities in `langium-cli` so it can be used as a library?

**Comment by spoenemann** [comment]
Duplicate of #174?

**Comment by spoenemann** [comment]
I tend to regard this as out of scope for Langium now. Shall we close this?

**Comment by montymxb** [comment]
I would agree for the 2nd & 3rd points at the least. We can always open up a more relevant issue should this come up, and target on that specific case. I'll close this out preemptively, we can always discuss this later (or in a dev meeting).
