### ISSUE TITLE
Ambiguous Handling of Duplicate Properties

### ISSUE THREAD

**Issue by montymxb** [eclipse-langium/langium#494]
## Issue Overview

for Langium version: 0.3.0 dev (post named cross-ref fix, #485 )

While looking into another Langium issue about duplicate properties in a hierarchy, I came across some strange behavior with duplicate properties. Take for the example the following rule:
```
X: prop=ID prop=ID
```
This shows no diagnostic, and successfully produces the following interface.
```ts
export interface X extends AstNode {
    prop: string
}
```
It appears that duplicate properties in a rule are implicitly rolled together into a single property of that type. That then begs the question, what about different types?
```
X: prop=ID prop=NUMBER;
```
generates...
```ts
export interface X extends AstNode {
    prop: number | string
}
```
Which seems to support the prior observation. And upon further checking it can be seen that something like `X: prop=(ID | NUMBER)` generates the equivalent interface in the AST.

However, this implicit unioning breaks down in special cases, such as for named cross refs. Consider the following recursive definition.
```
X: name=[X];
```
This can't be resolved as expected, and neither can an explicit union of this with a terminal of another type.
```
X: name=(ID | [X]);
```
Based on our observations before, we should expect that at least the implicit type unioning performed for duplicate properties should behave similarly. However, in practice, it does not.
```
X: name=ID name=[X]
```
generates...
```ts
export interface X extends AstNode {
    name: Reference<X> | number
}
```
Order matters in this context, as writing `X: name=[X] name=ID` will not work, same as the previously observed behavior.

Lastly, in the case of any other property name, cross-references to the the same rule do not work, even when unioned (explicitly or in this implicit case).

I suspect this is due to some special handling with the `name` property, and the way that inferred types are constructed.

## The expected behavior

Ideally, this behavior should be consistent regardless of the property name. Whether implicit unioning of duplicate types is desired, or not, it would be nice to enforce this. Additionally, order of special duplicate properties (like `name`) should not impact whether a type can be generated or not.

We could potentially resolve this by *dropping* named cross refs as a supported feature. In the current 0.3.0 release named cross refs don't work anyways, so perhaps this is a good way to proceed.

Also, we could disallow duplicate properties from being allowed, instead suggesting they be written as unions. But I'm not sure whether there is an established usage of this in any prior work.

**Comment by spoenemann** [comment]
There are separate issues here:

 * Multiple assignments to the same property (`prop=ID prop=ID`) should be marked with a warning because the value of the first assignment would be overwritten. This does not apply in alternatives (`prop=ID ... | prop=ID ...`), so we need to check every possible _path_ inside a rule.
 * I'd vote for disallowing the assignment of incompatible types to the same property when the type is inferred. This means we should never generate alternatives in property types (`prop: number | string`). Rationale: In most cases, I'd expect this to be unintended and thus an error. If you really want alternative types, either infer separate properties (`propA=ID propB=NUMBER`) or declare the type explicitly.

**Comment by Lotes** [comment]
I think we should disallow multiple assignments to the same property. We should have a clear and focused interface for the user. Adding to many options or sugar complicates the project.

**Comment by gfontorbe** [comment]
On that issue, for now it is also possible to assign a cross-reference and a DataType string rule to the same property. It results in an unexpected type in the AST:

```
A: value=([B:ID] | C)

B: name=ID;

C returns string: 'valueC' | 'otherValueC';
```

It generates:
```
interface C {
    value: Reference<B | string>
}
```

As mentioned by others, it should be forbidden to assign a cross-reference *and* a string to the same property

**Comment by msujew** [comment]
I believe we can close this. We have added a lot of validations in the meantime that solve a lot of these issues. If specific problem are still relevant, we should create more specific, new issues for those.
