### ISSUE TITLE
EBNF Negated Tokens Derive Incorrrect Regular Expressions

### ISSUE THREAD

**Issue by montymxb** [eclipse-langium/langium#681]
Langium version: pre-0.5.0

Langium supports EBNF style expressions in place of Regular Expressions. However, there appears to be an issue regarding how these expressions are converted in the case of negated tokens.

Take the following terminal with an EBNF expression, with a [negated token](https://www.eclipse.org/Xtext/documentation/301_grammarlanguage.html#negated-tokens).
```antlr
terminal NotA1: !('a');
```
And it's RegExp equivalent of a negated character class (for a single character this works, but not for negated sequences of 2 or more):
```antlr
terminal NotA2: /[^a]/;
```
In Langium we get the following:

<img width=500 src="https://user-images.githubusercontent.com/5070304/190666539-df5afb67-ba1e-4d1e-8963-c95abaf78537.jpg">

The generated RegExp that produces the error looks like so:
```regex
/((?!a)[\\s\\S]*?)/
```
The issue here is the the negative lookahead `(?! ...)` doesn't actually consume any characters. It simply guides the RegExp engine on how to proceed. The idea is right, since these tokens could be sequences of more than one character, and we can't just use a negated character class in such cases.

This is inserted by the following function.
https://github.com/langium/langium/blob/52ab0856ca2f1a7c71f45555783c504da3bb594d/packages/langium/src/grammar/grammar-util.ts#L284-L286

I sketched up a rough test case as well that can be used to verify a fix, which can go in **langium-grammar-validator.test.ts**.
```ts
test('EBNF Negated Tokens Produce Correct RegExp', async () => {
    const validationResult = await validate(`
    grammar G
    entry M: val=NotA;
    terminal NotA: !('a');
    `);
    expectNoIssues(validationResult);
});
```
A solution should accept any sequence that is not the given sequence, possibly with a `.`, but needs to apply the cardinality correctly.

**Comment by msujew** [comment]
I'm not sure whether I agree with this. I believe that `/[^a]/` and `!('a')` are semantically different. `/[^a]/` parses any single character except for `a`, while `!('a')` parses anything (even an empty string) except for `a`. In that sense the validation is correct, since the terminal can parse an empty string (among other strings). The `!` negated token is meant to be used with other tokens before and/or after that.

**Comment by montymxb** [comment]
Good point. When I get some time I would like to check this against Xtext, and see how the behavior is there. That would give a nice idea for how we should handle it in Langium, especially if that sequence should match an empty string.

**Comment by montymxb** [comment]
Following up, these are the existing behaviors for negated tokens in EBNF expressions.

**Xtext**: Converted to ANTLR. Is the set complement of characters (equiv to negated character class in RegEx). Exception is sequences of literals that are 2 or more characters long (ex. `!('abcd')`), which recognize *all* single character tokens due to complementing the empty set. This consumes input.
    - `!('a')` consumes any single character but 'a'
    - `!('abcd')` consumes any single character

**Langium**: Converted to RegEx. Is translated to negative lookeahead. This does *not* consume input.
    - `!('a')` negative lookahead on just 'a', _doesn't_ consume any input
    - `!('abcd')`negative lookahead on 'abcd', _doesn't_ consume any input

So, the semantics for the same expression in Xtext and Langium are not the same. We should at least document this, to avoid misleading users. We may also want to consider changing this to match with Xtext's behavior. This last point is important if the intent of supporting EBNF expressions is to make converting from Xtext to Langium easier.

**Comment by montymxb** [comment]
@msujew I think we should at least mark this as a `wont fix`, but not close it while it's still outstanding. I also think this doesn't necessary warrant attention right now since it's relatively non-impactful, but I wouldn't want to sweep it under the rug either.
