### ISSUE TITLE
Import DSL files as if they were written in TypeScript

### ISSUE THREAD

**Issue by Lotes** [eclipse-langium/langium#761]
The idea is to allow custom NodeJS import for domain-specific languages made with Langium. If Langium is the Xtext for the web, I think this would be a nice step to use it seamlessly. Here is an example…
Let's imagine a statemachine language with a file `TrafficLight.dsl`. We could import it with 

`import StateMachine, {Red, Green, Yellow} from "./TrafficLight.dsl";`

and execute it directly in TypeScript, like `myDslSysLib.execute(StateMachine)`. So the content of the DSL file creates statically typed concepts.
There are some times where I wished I had something like this. Of course you can put a TypeScript generation inbetween and debug then the generated code… but jumping to the DSL definition would be also nice.

* [ ] add tracing to a generator node API
* [ ] implement a JS map file generator for captured tracings

It should be possible to do something like this by generating `.js`, `.js.map`, `.d.ts` and `.d.ts.map` files. But I'm not sure how tsc and the TypeScript editor would behave, we should try.

**Comment by spoenemann** [comment]
We could create a new package for this, adding support for generating map files. I'm not sure how much we can do in general for the typings. Does the `typescript` package offer some API that we can use to build an in-memory type model and serialize it to .d.ts?

**Comment by msujew** [comment]
Since we already have a source-maps compatible generator, I'm not sure we can add more here for adopters. In the end, adopters would need to write a bundler plugin that transforms the import into compatible JavaScript.
