### ISSUE TITLE
Wrong validation message with subtype used in action

### ISSUE THREAD

**Issue by spoenemann** [eclipse-langium/langium#832]
The example mentioned in #815 does not work after the changes made in #819.

```
grammar Example

entry Model:
    examples+=Example*;

Example returns Example:
    {SpecificExample} 'example' name=ID 'using' parent=[Example:ID];

interface Example {
    parent: @Example
}

interface SpecificExample extends Example {
    name: string
}

hidden terminal WS: /\s+/;
terminal ID: /[_a-zA-Z][\w_]*/;
```

The shown validation errors look incorrect to me:
```
example.langium:6:1 - Inferred and declared versions of type Example both have to be interfaces or unions..
example.langium:9:11 - Inferred and declared versions of type Example both have to be interfaces or unions.
example.langium:13:35 - Interfaces cannot extend union types.
```

The errors disappear if the return type of `Example` is changed to `SpecificExample`.

**Comment by bjthehun** [comment]
At present, the grammar mentioned above does _not_ produce validation errors, and can be used to generate examples:

[Example832Demo.webm](https://github.com/eclipse-langium/langium/assets/38729215/718d9c23-13e3-41c9-b59e-fcc0b75f4805)

Therefore, this issue appears to have been resolved already.
