### ISSUE TITLE
IntelliJ example

### ISSUE THREAD

**Issue by ctron** [eclipse-langium/langium#999]
On the homepage it is mentioned that Langium can be used for IntelliJ editors. However, I wasn't able to find any information on how this could be achieved.

I think it makes sense to provide an example project, or at least outline the steps necessary.

**Comment by ben5311** [comment]
> On the homepage it is mentioned that Langium can be used for IntelliJ editors. However, I wasn't able to find any information on how this could be achieved.
> 
> I think it makes sense to provide an example project, or at least outline the steps necessary.

I have tried both the IntelliJ Marketplace Plugin https://plugins.jetbrains.com/plugin/10209-lsp-support and the IntelliJ Plugin dependency https://github.com/ballerina-platform/lsp4intellij.

The Marketplace Plugin is actually working: Validations, Quick Fixes, Formatting, etc.
But it crashes randomly and is not actively developed anymore.

With the lsp4intellij solution you need to setup you own IntelliJ extension project and integrate the Langium LSP server into it. It did not work for me, even though the project seems to be still alive. 
It does connect to the Langium LSP Server and I can even see that it receives notfications from it (e.g. on Hover) but it does not display it in the IntelliJ UI.

For me the IntelliJ LSP integration looks not really stable at the moment.
Also note that Syntax Highlighting usually does not work via LSP. Meaning you need to add Syntax Highlighting manually for IntelliJ / Eclipse / Other LSP editor.

**Comment by nadavhames** [comment]
Instead of IDEA, Jetbrains is coming out with Fleet soon which uses LSP, so support should be much easier for that product once it supports editor plugins.

**Comment by angelozerr** [comment]
Please try https://github.com/redhat-developer/lsp4ij which is a free lsp support for intellij

**Comment by Yokozuna59** [comment]
Fellows at [zenstack](https://github.com/zenstackhq/zenstack) were able to create the JetBrains extension:

- Original PR where the extension was created: https://github.com/zenstackhq/zenstack/pull/904
- The latest commit for the extension: https://github.com/zenstackhq/zenstack/tree/29962e0b48a73ae6d42f43f2575048ba9cf6a953/packages/ide/jetbrains

**Comment by spoenemann** [comment]
In the meantime, JetBrains has started offering LSP support for their paid IDEs: https://blog.jetbrains.com/platform/2023/07/lsp-for-plugin-developers/

As I understand this, the solution is not available for the open source IntelliJ Platform.

**Comment by spoenemann** [comment]
See also https://plugins.jetbrains.com/docs/intellij/language-server-protocol.html

**Comment by angelozerr** [comment]
@spoenemann as I said please try https://github.com/redhat-developer/lsp4ij which is a free lsp support for intellij which has been released.

If you want to try to integrate your language server without developping an IJ plugin please read https://github.com/redhat-developer/lsp4ij/blob/main/docs%2FUserDefinedLanguageServer.md

If you want to try to integrate your language server by developping an IJ plugin please read https://github.com/redhat-developer/lsp4ij/blob/main/docs%2FDeveloperGuide.md

If you want to know the LSP support please read https://github.com/redhat-developer/lsp4ij/blob/main/docs%2FLSPSupport.md

**Comment by angelozerr** [comment]
@spoenemann just for your information, we did the 0.0.2 release of LSP4IJ and if you want to have an overview of LSP4IJ, please read [Meet LSP4IJ, a new LSP Client for JetBrains-based IDEs](https://idetools.dev/blog/lsp4ij-announcement/) article that we have published on friday.

Hope you will like it.

**Comment by spoenemann** [comment]
Nice!

**Comment by msujew** [comment]
I've opened https://github.com/eclipse-langium/langium-website/issues/243 to track documentation on this. I think we should continue the discussion there. I'm closing this issue.

Thanks for the info about LSP4IJ, we'll surely include this on the website.
